export { default as Header } from '@/components/Header/Header.vue'
export { default as Button } from '@/components/common/Button/Button.vue'
export { default as RaceBoard } from './RaceBoard/RaceBoard.vue'
export { default as Horse } from '@/components/Icons/Horse.vue'
export { default as CLoseIcon } from './Icons/CLose.vue'
export { default as Drawer } from '@/components/common/Drawer/Drawer.vue'
export { default as RaceSchedule } from '@/components/RaceSchedule/RaceSchedule.vue'
export { default as RaceResults } from '@/components/RaceResult/RaceResult.vue'
export { default as Table } from '@/components/common/Table/Table.vue'
export {default as GeneralHorsList } from '@/components/GeneralHorsLits/GeneralHorsList.vue'
